# Generated by Django 3.0.7 on 2020-06-04 19:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='static/web/media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 19, 16, 15, 226482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 19, 16, 15, 227482, tzinfo=utc)),
        ),
    ]
