# Generated by Django 3.0.7 on 2020-07-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0003_auto_20200616_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=280),
        ),
    ]
